name: Manual Deploy Workflow

# Habilita o gatilho manual e define parâmetros de entrada
on:
  workflow_dispatch:
    inputs:      
      entrada:
        description: 'entrada'
        required: true
        type: string
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Usando os inputs que foram passados na chamada da API
      - name: Deploy to environment
        run: |
          echo "Iniciando deploy para o ambiente: ${{ github.event.inputs.entrada }}"
          echo "Deploy concluído!"