name: Manual Deploy Workflow

# Habilita o gatilho manual e define parâmetros de entrada
on:
  workflow_dispatch:
    inputs:      
      entrada:
        description: 'entrada'
        required: true
        type: string
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Usando os inputs que foram passados na chamada da API

      - name: Parse JSON string from input
        id: parse_json # Damos um ID a este passo para referenciar seus outputs
        run: |
          echo "ref=${{ fromJson(github.event.inputs.entrada).ref }}" >> $GITHUB_OUTPUT
          echo "input_env=${{ fromJson(github.event.inputs.entrada).inputs.environment }}" >> $GITHUB_OUTPUT


      - name: Deploy to environment
        run: |
          echo "ref: ${{ steps.parse_json.outputs.ref }}"
          echo "Iniciando deploy para o ambiente: ${{ steps.parse_json.outputs.input_env }}"
          echo "Deploy concluído!"
